language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install pytest
script: py.test
deploy:
  provider: pypi
  user: abhsag
  password:
    secure: qawYSbj6GgWjlMKsIYp6uadA5z+1gzrnG88TusGdNS5GbLkaHwY6MsleZG7OVXsUPkI2FaH3em/mnQfVC6tfHczrSTrnwUZMPAabKA+T8j6H/WlkTOpJCRqnWAsTdnr8RM/h55LdKNQ4JeGG/eI5CRvrV5XZsRbYM0/A9Txd/yThX8YwBEKF45+r57j9IREvHW0TkoGANMxk/ubWyY9UcGSsEDOjjeJpODOWy0kF6LpVM69wB57NrENm4V76kV57zBOfGkfe42YkfLxJDrbrLnNHsBXF23gz+mkuquwCJbHzOUKDCSbuo54L1ho6q3YbMFjiNDz/JNRL23njM2k0+fXDuX6fMtqRyP4shIGsrM6BSsfu/m6pIy/8XJcKprtigNtZ47imipllXS+KKQRZU5NecUO00/4rvxYljBs00b7c9YSD9SDovjGNRakp62WabNOhZ3IUYZxRwhVikIQUfKJvDTJCQXSuNMyzn87y+OfTGkSSkUZWLRKnHswo1tskY2PugdMDDUaWGubNj9piQht3Yzdg9wKuxkVuP9aNUFPdbU3uRamE9s5n6smsrU8LYfDwiMut3oxeyuyA9uPSDpz9S0tYciXJOZWRCJ+vCctayZwWhG6yvSjz0d9oENBOWu6HjqN30IROHLKAfmou4suVULWnTNr+WzcMZiExXI0=
